server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jia_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  main:
    allow-circular-references: true
  redis:
    database: 0
    timeout : 5000
    host: 8.130.50.102
    port: 6379
    password: 20010124
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: kS5B2o9DUhM6Q2uWlK4aNhvoZxVLDl1H1oMXfs0S
  secretKey: JIUtDjtDdP_0fyJPzwZptZYVKbs8vvQAWmiseqaR
  bucket: q42316519
